### ISSUE TITLE
Subprocesses are not terminated when the parent process exits

### ISSUE THREAD

**Issue by jspahrsummers** [Carthage/ReactiveTask#3]
Originally reported and discussed in https://github.com/Carthage/Carthage/issues/89. The most notable comment is this:

> From a lot of Googling and consulting with @keithduncan, it appears that `NSTask` is a special :hankey::snowflake: in this scenario, and spawns processes outside of the parent's process group. The same problem supposedly wouldn't arise with `fork()` or `posix_spawn()` directly.

**Comment by ikesyo** [comment]
Using the `NSConcreteTask.setStartsNewProcessGroup` private API would be the solution, which is used in various projects:

- https://github.com/facebook/xctool/blob/26a20314dcef4c238012889fbe37b767ec5719ca/Common/TaskUtil.m#L440-L459
- https://github.com/CrossWaterBridge/xctool-runner/blob/b2f0aac94a8c19f033e3f39df4c2e718403b5aab/xctool-runner.swift#L20-L34
- https://chromium.googlesource.com/chromium/src/+/4884682f47e2c9f0c5b193e6d531714821dd8ffc/testing/iossim/iossim.mm#69
