### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by mdiep** [Carthage/ReactiveTask#49]
I really want to get the recent API changes and the RAC updates into Carthage. Would anyone object to me releasing `master` as `0.9`?

**Comment by mdiep** [comment]
(It looks like https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2453 is at least partially to blame for https://github.com/Carthage/Carthage/issues/940.)

**Comment by NachoSoto** [comment]
👍 ship it

**Comment by ikesyo** [comment]
:+1: from me

**Comment by mdiep** [comment]
[Released!](https://github.com/Carthage/ReactiveTask/releases/tag/0.9) :tada:
